CREATE TABLE IF NOT EXISTS FLYWAY_BOOTSTRAP (
  ID INT PRIMARY KEY,
  NOTE VARCHAR(255) NOT NULL
);

INSERT INTO FLYWAY_BOOTSTRAP (ID, NOTE)
VALUES (1, 'Initial Flyway bootstrap migration for PR2 skeleton')
ON DUPLICATE KEY UPDATE NOTE = VALUES(NOTE);
