use vbb;
SET FOREIGN_KEY_CHECKS = 0;
drop table if exists BUCHUNG, SPIELER, SPIEL, SEASON, USERS, ROLES, CONFIG, MAILS, JOURNAL cascade;
drop view if exists V_USER_ROLE;
SET FOREIGN_KEY_CHECKS = 1;

create table JOURNAL (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	BUSINESS_CASE VARCHAR(64),
	DESCRIPTION VARCHAR(255),
	USERID VARCHAR(128),
	TMS TIMESTAMP, 
	PRIMARY KEY (ID)
);

create table SEASON (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION VARCHAR(255),
	STARTDATE DATE, 
	ENDDATE DATE, 
	PRICE DECIMAL(4,2),
	LKZ CHAR DEFAULT 'N',
	PRIMARY KEY (ID)
	
);

create table SPIEL (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	DATUM DATE,
	SEASON_ID INTEGER,
	LKZ CHAR DEFAULT 'N',
	PRIMARY KEY (ID),
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(ID)
);

create table SPIELER (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	NAME VARCHAR(40) unique,
    EMAIL varchar(255),
    ACTIVITYLEVEL INTEGER,
	PRIMARY KEY (ID)
);

create table BUCHUNG (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	SPIEL_ID INTEGER,
	DATUM TIMESTAMP,
	SPIELER_ID INTEGER,
	DESCRIPTION VARCHAR(255),
	PRICE DECIMAL(10,5),
	LKZ CHAR NOT NULL DEFAULT 'N',
	ITMS TIMESTAMP,
	UTMS TIMESTAMP,
	PRIMARY KEY (ID),
	FOREIGN KEY (SPIEL_ID) REFERENCES SPIEL(ID),
	FOREIGN KEY (SPIELER_ID) REFERENCES SPIELER(ID)
);

create table ROLES (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	NAME VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR (255),
	PRIMARY KEY (ID)
);

create table USERS (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	USERID VARCHAR(128) UNIQUE NOT NULL,
	USERNAME VARCHAR (255),
	EMAIL VARCHAR (128) UNIQUE NOT NULL,
	PASSWORD VARCHAR (255) NOT NULL,
	STATE VARCHAR(16),
	REGID VARCHAR(36) UNIQUE,
	GROUP_ID INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (GROUP_ID) REFERENCES ROLES(ID)
);


CREATE VIEW V_USER_ROLE AS
SELECT  u.USERID, u.PASSWORD, g.NAME
 FROM USERS u
 INNER JOIN ROLES g ON g.ID =  u.GROUP_ID; 

create table CONFIG (
	ID INTEGER NOT NULL AUTO_INCREMENT, 
	CONFIGKEY VARCHAR(64) UNIQUE,
	CONFIGVALUE VARCHAR (512),
	PRIMARY KEY (ID)
);

create table MAILS (
	ID INTEGER NOT NULL AUTO_INCREMENT,
	RECIPIENT VARCHAR (255) NOT NULL,
	SUBJECT VARCHAR(255) NOT NULL,
	TEXT VARCHAR (4096) NOT NULL,
	ATTEMPT INTEGER,
	PRIMARY KEY(ID)
);
