ALTER TABLE BUCHUNG DROP FOREIGN KEY FK_BUCHUNG_SPIEL_ID;
ALTER TABLE BUCHUNG DROP FOREIGN KEY FK_BUCHUNG_SPIELER_ID;
ALTER TABLE SPIEL DROP FOREIGN KEY FK_SPIEL_SEASON_ID
ALTER TABLE TOKEN DROP FOREIGN KEY FK_TOKEN_USER_ID
ALTER TABLE USER_GROUP DROP FOREIGN KEY FK_USER_GROUP_GROUP_ID
ALTER TABLE USER_GROUP DROP FOREIGN KEY FK_USER_GROUP_USER_ID
DROP TABLE BUCHUNG
DROP TABLE CONFIG
DROP TABLE SEASON
DROP TABLE SPIEL
DROP TABLE SPIELER
DROP TABLE USERS
DROP TABLE ROLES
DROP TABLE MAILS
DROP TABLE TOKEN
DROP TABLE USER_GROUP
