drop table BUCHUNG;
drop table SPIELER;
drop table SPIEL;
drop table SEASON;
drop view V_USER_ROLE;
drop table USERS;
drop table GROUPS;
drop table CONFIG;
drop table MAILS;

create table SEASON (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DESCRIPTION VARCHAR(255),
	STARTDATE DATE, 
	ENDDATE DATE, 
	PRICE DECIMAL(4,2),
	LKZ CHAR DEFAULT 'N',
	PRIMARY KEY (ID)
);

create table SPIEL (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	DATUM DATE,
	SEASON_ID INTEGER,
	LKZ CHAR DEFAULT 'N',
	PRIMARY KEY (ID),
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON(ID)
);

create table SPIELER (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(255) unique,
    EMAIL varchar(255),
	PRIMARY KEY (ID)
);

create table BUCHUNG (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	SPIEL_ID INTEGER,
	DATUM TIMESTAMP,
	SPIELER_ID INTEGER,
	DESCRIPTION VARCHAR(255),
	PRICE DECIMAL(10,5),
	LKZ CHAR NOT NULL DEFAULT 'N',
	PRIMARY KEY (ID),
	FOREIGN KEY (SPIEL_ID) REFERENCES SPIEL(ID),
	FOREIGN KEY (SPIELER_ID) REFERENCES SPIELER(ID)
);

create table GROUPS (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	NAME VARCHAR(20) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR (255),
	PRIMARY KEY (ID)
);

create table USERS (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERID VARCHAR(255) UNIQUE NOT NULL,
	USERNAME VARCHAR (255),
	EMAIL VARCHAR (255) UNIQUE NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	STATE VARCHAR(16),
	REGID VARCHAR(255) UNIQUE,
	GROUP_ID INT REFERENCES GROUPS(ID),
	PRIMARY KEY (ID)
);


CREATE VIEW V_USER_ROLE AS
SELECT  u.USERID, u.PASSWORD, g.NAME
 FROM USERS u
 INNER JOIN GROUPS g ON g.ID =  u.GROUP_ID; 

create table CONFIG (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	CONFIGKEY VARCHAR(255) UNIQUE,
	CONFIGVALUE VARCHAR (512),
	PRIMARY KEY (ID)
);

create table MAILS (
	id int not null  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	RECIPIENT VARCHAR (255) NOT NULL,
	SUBJECT VARCHAR(255) NOT NULL,
	TEXT VARCHAR (4096) NOT NULL,
	ATTEMPT INTEGER,
	PRIMARY KEY(ID)
);
