pipeline {
    agent any
    tools { 
        maven 'Maven 3.6.1' 
        jdk 'JDK 11' 
    }
    stages {
       stage ('Build') {
            steps {
					sh 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
            	        junit 'target/surefire-reports/**/*.xml' 
                }
            }
       }
	   
       stage ('Checkstyle') {
            steps {
	                sh 'mvn -Dmaven.test.failure.ignore=true checkstyle:checkstyle' 
            }
            post {
			   always {
				   step([$class: 'hudson.plugins.checkstyle.CheckStylePublisher', checkstyle: 'gitlist-PHP/build/logs/phpcs.xml'])
			   }
            }
       }
       stage('JaCoCo') {
	     steps {
                sh 'mvn -Dmaven.test.failure.ignore=true jacoco:prepare-agent verify' 
	        step( [ $class: 'JacocoPublisher' ] )
	     }
}
	   stage ('Site') {
		   steps {
			   		sh 'mvn -Dmaven.test.failure.ignore=true site'
		   }
	   }
    }
}
