pipeline {
    agent any
    tools { 
        maven 'Maven 3.6.1' 
        jdk 'JDK 11' 
    }
    stages {
       stage ('Build') {
            steps {
				dir("vbbproject") {
					sh 'mvn -Dmaven.test.failure.ignore=true install' 
		 		}
            }
            post {
                success {
					dir("vbbproject") {
            	        junit 'target/surefire-reports/**/*.xml' 
					}
                }
            }
       }
	   
       stage ('Checkstyle') {
            steps {
		    	dir("vbbproject") {
	                sh 'mvn -Dmaven.test.failure.ignore=true checkstyle:checkstyle' 
				}
            }
            post {
			   always {
				   step([$class: 'hudson.plugins.checkstyle.CheckStylePublisher', checkstyle: 'gitlist-PHP/build/logs/phpcs.xml'])
			   }
            }
       }
       stage('JaCoCo') {
	     steps {
	    	dir("vbbproject") {
                sh 'mvn -Dmaven.test.failure.ignore=true verify' 
			}
	        step( [ $class: 'JacocoPublisher' ] )
	     }
}
	   stage ('Site') {
		   steps {
				dir("vbbproject") {
			   		sh 'mvn -Dmaven.test.failure.ignore=true site'
				}
		   }
	   }
    }
}
