spring:
  application:
    name: vbb-next
  datasource:
    url: jdbc:postgresql://localhost:5432/vbb
    username: vbb
    password: vbb
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
